<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customBlock = $objectManager->get('\Wow\ExcludeDiscountProduct\Block\Product');

$_productCollection = $block->getLoadedProductCollection();
$_productCollection = $customBlock->adjustCollection($_productCollection);
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');

/** Wow_CategoryPermission  */
$categoryPermissionHelper = $this->helper('Wow\CategoryPermission\Helper\Data');
$categoryId = $block->getLayer()->getCurrentCategory()->getId();
$categoryPermission = $categoryPermissionHelper->getCategoryPermissionStatus($categoryId);
?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else : ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }

    $currentStore = $customBlock->getCurrentStore()->getCode();
    $exclCat = $customBlock->getExcludeCategory();

    $writer = new \Zend_Log_Writer_Stream(BP.'/var/log/reza-test.log');
    $logger = new \Zend_Log();
    $logger->addWriter($writer);
    


    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php if($currentStore=="coachsgrt_en") : ?>
                <?php foreach ($_productCollection as $_product) : ?>                    
                    <?php 
                        $style = "display: inline-block !important;";
                        if($exclCat && $exclCat == $categoryId){
                            if($_product->getTypeId() == "configurable"){
                                $childProducts = $_product->getTypeInstance()->getUsedProducts($_product);
                                foreach ($childProducts as $simpleProduct){
                                    $orgprice = $simpleProduct->getPrice();
                                    $finalPrice = $simpleProduct->getFinalPrice();
                                    if($finalPrice >= $orgprice){
                                        $style = "display: none !important;";
                                    }else{
                                        $style = "display: inline-block !important;";
                                        break;
                                    }
                                    
                                }
                            }else{
                                $orgprice = $_product->getPrice();
                                $finalPrice = $_product->getFinalPrice();
                                if($finalPrice >= $orgprice){
                                    $style = "display: none !important;";
                                }
                            }
                        }
                    ?>
                    <li class="item product product-item" style="<?= /* @noEscape */ $style ?>">
                        <div class="product-item-info" id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                            <?php
                            $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = 'left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;';
                            }
                            ?>
                            <?php // Product Image 
                            ?>

                            <div class="product-image-section">
                                
                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?= $productImage->toHtml() ?>
                                    <div class="product-label-container">
                                        <?php
                                        $labelBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Wow\ProductLabel\Block\Label');
                                        $labelArray = $labelBlock->getLabelArray($_product->getSku(), 'Product Image');
                                        foreach($labelArray as $la) {
                                            echo "<div class='item-label' style='color:".$la['color']."; background: ".$la['bg_color']."'>".$la['labelname']."</div>";
                                        }

                                        ?>
                                    </div>
                                </a>

                                <?php if (!($categoryPermissionHelper->isEnable() && !$categoryPermission)): ?>
                                    <div data-role="add-to-links" class="actions-secondary addto-wishlist">
                                        <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <?= strpos($pos ?? '', $viewMode . '-secondary') ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                    ) : '' ?>
                            </div>
                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                        <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                <?php if ($_product->isAvailable()) : ?>
                                    <?= $block->getProductDetailsHtml($_product) ?>
                                <?php endif; ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()) : ?>
                                                <?php if (!($categoryPermissionHelper->isEnable() && !$categoryPermission)): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>" action="<?= $escaper->escapeUrl($postParams['action']) ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart primary" id="product-addtocart-button">
                                                            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php endif; ?>
                                            <?php else : ?>
                                                <?php if ($_product->isAvailable()) : ?>
                                                    <div class="stock available">
                                                        <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                                    </div>
                                                <?php else : ?>
                                                    <div class="stock unavailable">
                                                        <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <?= strpos($pos ?? '', $viewMode . '-primary') ?
                                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                                $position,
                                                'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                            ) : '' ?>
                                    </div>
                                    <?php if ($showDescription) : ?>
                                        <div class="product description product-item-description">
                                            <?= /* @noEscape */ $_helper->productAttribute(
                                                $_product,
                                                $_product->getShortDescription(),
                                                'short_description'
                                            ) ?>
                                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" title="<?= /* @noEscape */ $_productNameStripped ?>" class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?= strpos($pos ?? '', $viewMode . '-actions') ?
                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                $position,
                                'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                            ) : '' ?>
                    </li>

                <?php endforeach; ?>

            <?php else : ?>
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product) : ?>
                    <li class="item product product-item">
                        <div class="product-item-info" id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                            <?php
                            $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = 'left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;';
                            }
                            ?>
                            <?php // Product Image 
                            ?>

                            <div class="product-image-section">
                                
                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?= $productImage->toHtml() ?>
                                    <div class="product-label-container">
                                        <?php
                                        $labelBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Wow\ProductLabel\Block\Label');
                                        $labelArray = $labelBlock->getLabelArray($_product->getSku(), 'Product Image');
                                        foreach($labelArray as $la) {
                                            echo "<div class='item-label' style='color:".$la['color']."; background: ".$la['bg_color']."'>".$la['labelname']."</div>";
                                        }

                                        ?>
                                    </div>
                                </a>

                                <?php if (!($categoryPermissionHelper->isEnable() && !$categoryPermission)): ?>
                                    <div data-role="add-to-links" class="actions-secondary addto-wishlist">
                                        <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <?= strpos($pos ?? '', $viewMode . '-secondary') ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                    ) : '' ?>
                            </div>
                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                        <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                <?php if ($_product->isAvailable()) : ?>
                                    <?= $block->getProductDetailsHtml($_product) ?>
                                <?php endif; ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()) : ?>
                                                <?php if (!($categoryPermissionHelper->isEnable() && !$categoryPermission)): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>" action="<?= $escaper->escapeUrl($postParams['action']) ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart primary" id="product-addtocart-button">
                                                            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php endif; ?>
                                            <?php else : ?>
                                                <?php if ($_product->isAvailable()) : ?>
                                                    <div class="stock available">
                                                        <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                                    </div>
                                                <?php else : ?>
                                                    <div class="stock unavailable">
                                                        <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <?= strpos($pos ?? '', $viewMode . '-primary') ?
                                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                                $position,
                                                'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                            ) : '' ?>
                                    </div>
                                    <?php if ($showDescription) : ?>
                                        <div class="product description product-item-description">
                                            <?= /* @noEscape */ $_helper->productAttribute(
                                                $_product,
                                                $_product->getShortDescription(),
                                                'short_description'
                                            ) ?>
                                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" title="<?= /* @noEscape */ $_productNameStripped ?>" class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?= strpos($pos ?? '', $viewMode . '-actions') ?
                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                $position,
                                'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                            ) : '' ?>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>